### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by ZChenzy** [CrystalFerrai/Ue4Export#1]
hey I am not sure why I am hitting this:

I have .NET 6.0 sdk installed

![image](https://github.com/CrystalFerrai/Ue4Export/assets/30629529/10f5fc18-b3e3-461a-9d41-1b47fc2945b7)

**Comment by CrystalFerrai** [comment]
The issue is that those files are compressed with Oodle compression which was not supported at the time. I have just released version 2.5.0 which adds Oodle support. The new version also requires installing .net 8.

**Comment by CrystalFerrai** [comment]
Note: 2.5.0 was missing a DLL so skip that. Version 3.0.1 should fully work.
